Everything up to "Gradient Descent Vector Style" is copied from Nicholas Renotte


Source:https://www.youtube.com/watch?v=Souzjv6WfrY&t=816s

In [117]:
import numpy as np

In [118]:
x=np.random.randn(10,1)

In [119]:
print(x)

[[-0.25900344]
 [ 0.84519776]
 [ 0.99586785]
 [ 0.65810021]
 [-0.30027708]
 [ 0.78027012]
 [ 0.02491361]
 [ 0.11546709]
 [-1.26499148]
 [-0.30144655]]


In [120]:
y=2*x + np.random.rand()
##random calculation to represent y

In [121]:
y

array([[ 0.35669858],
       [ 2.56510099],
       [ 2.86644115],
       [ 2.19090588],
       [ 0.27415129],
       [ 2.4352457 ],
       [ 0.92453267],
       [ 1.10563963],
       [-1.6552775 ],
       [ 0.27181236]])

In [122]:
w=1.0
b=1.0
learning_rate=0.1

#  Gradient Descent (non-vector way)

In [123]:
def descent(x,y,w,b,learning_rate):
    dldw=0.0
    dldb=0.0
    N=x.shape[0]
    
    
    for xi, yi in zip(x,y):
        dldw +=-2*xi * (yi-(w*xi+b))
        dldb+= -2 * (yi-(w*xi+b))
        
    w=w-learning_rate*(1/N) * dldw
    b= b-learning_rate*(1/N) * dldb
    return w,b

In [124]:
for epoch in range(300):
    w, b= descent(x,y,w,b,learning_rate)
    yhat=w*x + b
    

#  Gradient Descent Vector Style

In [1040]:
import numpy as np

In [1041]:
x=np.array

In [1042]:
from numpy.random import rand

In [1043]:
x=rand(20)

In [1044]:
x=x.reshape(10,2)
x

array([[0.3663037 , 0.04108482],
       [0.01289677, 0.65268134],
       [0.97981633, 0.69158432],
       [0.64262064, 0.20972312],
       [0.90454786, 0.14147465],
       [0.09043167, 0.95277419],
       [0.11143006, 0.73306164],
       [0.01146716, 0.88795838],
       [0.20053835, 0.90520271],
       [0.15132595, 0.11841118]])

In [1045]:
intercept=np.array([[1],[1],[1],[1],[1],[1],[1],[1],[1],[1]])

In [1046]:
x=np.concatenate((intercept,x),axis=1)

In [1047]:
x

array([[1.        , 0.3663037 , 0.04108482],
       [1.        , 0.01289677, 0.65268134],
       [1.        , 0.97981633, 0.69158432],
       [1.        , 0.64262064, 0.20972312],
       [1.        , 0.90454786, 0.14147465],
       [1.        , 0.09043167, 0.95277419],
       [1.        , 0.11143006, 0.73306164],
       [1.        , 0.01146716, 0.88795838],
       [1.        , 0.20053835, 0.90520271],
       [1.        , 0.15132595, 0.11841118]])

In [1048]:
y=rand(10)

In [1049]:
y

array([0.2657379 , 0.31345832, 0.63485203, 0.94592489, 0.88724828,
       0.10727525, 0.76469315, 0.25362683, 0.94554945, 0.02761306])

In [1050]:
y=y.reshape(len(y),1)

In [1051]:
x.shape

(10, 3)

In [1052]:
y=y.reshape(len(y),1)
y.shape

(10, 1)

In [1053]:
w=np.array([[1],[1],[1]])
learning_rate=0.01
n=x.shape[0]
print(w.shape)

(3, 1)


In [1054]:
def gradient(x,y,w,n,learning_rate):
    dldw=np.array([[0.0],[0.0],[0.0]])
    for xi, yi in zip(x,y):
        e=np.transpose(xi)
        e=e.reshape(1,3)
        dldw=np.add(dldw, ((-2/n)*e * (yi-(xi*w))))
    w=w- (learning_rate*dldw)
    w=w[1,:]
    return w

In [1056]:
for epochs in range(300):
    w=gradient(x,y,w,n,learning_rate)
    yhat=x*w
    error=np.square(y-yhat)
    error=np.sum(error)
    print(error)
    print()
    print()
    

7.180012455587313


7.083661786649809


6.990968047801067


6.901788974450301


6.815987894677719


6.733433508424237


6.653999675414681


6.57756521146879


6.504013692868027


6.433233268459386


6.365116479189917


6.299560084777923


6.236464897238358


6.175735620991132


6.117280699291828


6.061012166734587


6.006845507586863


5.954699519725263


5.904496183950757


5.856160538470456


5.809620558341445


5.764807039680306


5.721653488449805


5.680096013641515


5.640073224680542


5.601526132885188


5.564398056821175


5.5286345313962695


5.494183220547348


5.460993833377755


5.429018043608421


5.398209412211657


5.368523313101681


5.339916861760964


5.312348846686232


5.285779663542579


5.2601712519185515


5.235487034579325


5.211691859119137


5.188751941918064


5.166634814312017


5.145309270888376


5.124745319823201


5.10491413517928


5.085788011087439


5.067340317736632


5.049545459101287


5.032378832337184


5.015816788779902


4.999836596482431


