Everything up to "Gradient Descent Vector Style" is copied from Nicholas Renotte


Source:https://www.youtube.com/watch?v=Souzjv6WfrY&t=816s

In [117]:
import numpy as np

In [118]:
x=np.random.randn(10,1)

In [119]:
print(x)

[[-0.25900344]
 [ 0.84519776]
 [ 0.99586785]
 [ 0.65810021]
 [-0.30027708]
 [ 0.78027012]
 [ 0.02491361]
 [ 0.11546709]
 [-1.26499148]
 [-0.30144655]]


In [120]:
y=2*x + np.random.rand()
##random calculation to represent y

In [121]:
y

array([[ 0.35669858],
       [ 2.56510099],
       [ 2.86644115],
       [ 2.19090588],
       [ 0.27415129],
       [ 2.4352457 ],
       [ 0.92453267],
       [ 1.10563963],
       [-1.6552775 ],
       [ 0.27181236]])

In [122]:
w=1.0
b=1.0
learning_rate=0.1

#  Gradient Descent (non-vector way)

In [123]:
def descent(x,y,w,b,learning_rate):
    dldw=0.0
    dldb=0.0
    N=x.shape[0]
    
    
    for xi, yi in zip(x,y):
        dldw +=-2*xi * (yi-(w*xi+b))
        dldb+= -2 * (yi-(w*xi+b))
        
    w=w-learning_rate*(1/N) * dldw
    b= b-learning_rate*(1/N) * dldb
    return w,b

In [124]:
for epoch in range(300):
    w, b= descent(x,y,w,b,learning_rate)
    yhat=w*x + b
    

#  Gradient Descent Vector Style

In [227]:
import numpy as np

In [228]:
x=np.array

In [229]:
from numpy.random import rand

In [230]:
x=rand(100)

In [231]:
intercept.shape

(1, 10)

In [232]:
x=x.reshape(10,10)
x

array([[0.39015689, 0.79532628, 0.79047981, 0.21450864, 0.62302353,
        0.68590519, 0.5447275 , 0.06513042, 0.41486404, 0.93820253],
       [0.20025561, 0.25645628, 0.72663967, 0.85243533, 0.95878626,
        0.62349965, 0.63671041, 0.07474471, 0.96495532, 0.18337084],
       [0.62647987, 0.13542761, 0.20331853, 0.20638949, 0.14282684,
        0.54919247, 0.08865015, 0.9152436 , 0.78316063, 0.95635433],
       [0.36648617, 0.73888383, 0.04524276, 0.57929079, 0.16227157,
        0.43513474, 0.91225717, 0.65105942, 0.91924463, 0.87930868],
       [0.68093911, 0.02742413, 0.62104454, 0.2039256 , 0.72426301,
        0.81480856, 0.5859814 , 0.52629863, 0.87489086, 0.96216214],
       [0.43005123, 0.48984437, 0.7353426 , 0.5614171 , 0.26478531,
        0.85690752, 0.67682689, 0.89802486, 0.45501163, 0.2779388 ],
       [0.59101134, 0.20852804, 0.08840914, 0.85876116, 0.47889801,
        0.9452034 , 0.20069006, 0.94443708, 0.53272974, 0.52873095],
       [0.38838311, 0.46259925, 0.5250808

In [233]:
intercept=np.array([[1,1,1,1,1,1,1,1,1,1]])

In [234]:
intercept.shape

(1, 10)

In [235]:
x=np.concatenate((intercept,x))

In [236]:
x

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.39015689, 0.79532628, 0.79047981, 0.21450864, 0.62302353,
        0.68590519, 0.5447275 , 0.06513042, 0.41486404, 0.93820253],
       [0.20025561, 0.25645628, 0.72663967, 0.85243533, 0.95878626,
        0.62349965, 0.63671041, 0.07474471, 0.96495532, 0.18337084],
       [0.62647987, 0.13542761, 0.20331853, 0.20638949, 0.14282684,
        0.54919247, 0.08865015, 0.9152436 , 0.78316063, 0.95635433],
       [0.36648617, 0.73888383, 0.04524276, 0.57929079, 0.16227157,
        0.43513474, 0.91225717, 0.65105942, 0.91924463, 0.87930868],
       [0.68093911, 0.02742413, 0.62104454, 0.2039256 , 0.72426301,
        0.81480856, 0.5859814 , 0.52629863, 0.87489086, 0.96216214],
       [0.43005123, 0.48984437, 0.7353426 , 0.5614171 , 0.26478531,
        0.85690752, 0.67682689, 0.89802486, 0.45501163, 0.2779388 ],
       [0.59101134, 0.20852804, 0.0884091

In [237]:
y=rand(11)

In [238]:
y

array([0.72817788, 0.83465456, 0.61768271, 0.60229886, 0.98890057,
       0.39294535, 0.7243055 , 0.91442654, 0.25569718, 0.98173505,
       0.28999175])

In [239]:
x.shape

(11, 10)

In [240]:
y=y.reshape(len(y),1)
y.shape

(11, 1)

In [241]:
w=np.array([[1,1,1,1,1,1,1,1,1,1]])
learning_rate=0.01
n=x.shape[0]

In [242]:
def gradient(x,y,w,n,learning_rate):
    dldw=0
    for xi, yi in zip(x,y):
        dldw+=(-2/n) * np.transpose(xi) * (yi-(xi*w))
    w=w- (learning_rate*dldw)
    return w

In [243]:
for epochs in range(300):
    w=gradient(x,y,w,n,learning_rate)
    yhat=x*w
    error=np.square(y-yhat)
    error=np.sum(error)
    print(error)
    print()
    print()

18.447472466128204


18.426685694969528


18.406323527508658


18.38637713783905


18.36683788582089


18.34769731313533


18.3289471394231


18.310579258505676


18.29258573468724


18.274958799135717


18.25769084634114


18.24077443064974


18.224202262872044


18.207967206963552


18.19206227677625


18.17648063287952


18.161215579449024


18.146260561221958


18.131609160517353


18.117255094320065


18.10319221142689


18.089414489653716


18.075916033102274


18.06269106948512


18.04973394750786


18.037039134307097


18.024601212943132


18.012414879946043


18.000474942914256


17.98877631816414


17.97731402842992


17.96608320061247


17.955079063576196


17.944296945992818


17.933732274231144


17.923380570291823


17.913237449786042


17.903298619957354


17.893559877745624


17.884017107892166


17.874666281085318


17.865503452145408


17.85652475824845


17.847726417187587


17.839104725671575


17.83065605765948


17.822376862730774


17.814263664490156


17.8063130