Everything up to "Gradient Descent Vector Style" is copied from Nicholas Renotte


Source:https://www.youtube.com/watch?v=Souzjv6WfrY&t=816s

In [117]:
import numpy as np

In [118]:
x=np.random.randn(10,1)

In [119]:
print(x)

[[-0.25900344]
 [ 0.84519776]
 [ 0.99586785]
 [ 0.65810021]
 [-0.30027708]
 [ 0.78027012]
 [ 0.02491361]
 [ 0.11546709]
 [-1.26499148]
 [-0.30144655]]


In [120]:
y=2*x + np.random.rand()
##random calculation to represent y

In [121]:
y

array([[ 0.35669858],
       [ 2.56510099],
       [ 2.86644115],
       [ 2.19090588],
       [ 0.27415129],
       [ 2.4352457 ],
       [ 0.92453267],
       [ 1.10563963],
       [-1.6552775 ],
       [ 0.27181236]])

In [122]:
w=1.0
b=1.0
learning_rate=0.1

#  Gradient Descent (non-vector way)

In [123]:
def descent(x,y,w,b,learning_rate):
    dldw=0.0
    dldb=0.0
    N=x.shape[0]
    
    
    for xi, yi in zip(x,y):
        dldw +=-2*xi * (yi-(w*xi+b))
        dldb+= -2 * (yi-(w*xi+b))
        
    w=w-learning_rate*(1/N) * dldw
    b= b-learning_rate*(1/N) * dldb
    return w,b

In [124]:
for epoch in range(300):
    w, b= descent(x,y,w,b,learning_rate)
    yhat=w*x + b
    

#  Gradient Descent Vector Style

In [143]:
import numpy as np

In [144]:
x=np.array

In [145]:
from numpy.random import rand

In [146]:
x=rand(100)

In [147]:
intercept.shape

(1, 10)

In [148]:
x=x.reshape(10,10)
x

array([[0.15635825, 0.59623496, 0.28556072, 0.94199277, 0.06853796,
        0.5115061 , 0.62428826, 0.92265798, 0.43192345, 0.28721938],
       [0.16853195, 0.4063734 , 0.14626227, 0.68302495, 0.26418672,
        0.89601141, 0.77045393, 0.28097726, 0.6324734 , 0.06162585],
       [0.02416492, 0.08694826, 0.21949649, 0.20122716, 0.88249181,
        0.50616996, 0.8993781 , 0.95710921, 0.63770942, 0.68241222],
       [0.90908665, 0.76966646, 0.59840982, 0.33413361, 0.13269855,
        0.97599439, 0.39864375, 0.79847966, 0.2953324 , 0.12213067],
       [0.20645804, 0.88750785, 0.15048484, 0.30047141, 0.43458025,
        0.35494665, 0.69618276, 0.84114557, 0.55308782, 0.84199618],
       [0.54028794, 0.00700666, 0.461035  , 0.48441452, 0.40104222,
        0.15401944, 0.77371657, 0.58172054, 0.47219237, 0.19823101],
       [0.22885836, 0.68100159, 0.39473115, 0.29377908, 0.6493931 ,
        0.24560344, 0.56971802, 0.68127699, 0.02304456, 0.3063414 ],
       [0.36935427, 0.28790353, 0.2266356

In [149]:
intercept=np.array([[1,1,1,1,1,1,1,1,1,1]])

In [150]:
intercept.shape

(1, 10)

In [151]:
x=np.concatenate((intercept,x))

In [152]:
x

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.15635825, 0.59623496, 0.28556072, 0.94199277, 0.06853796,
        0.5115061 , 0.62428826, 0.92265798, 0.43192345, 0.28721938],
       [0.16853195, 0.4063734 , 0.14626227, 0.68302495, 0.26418672,
        0.89601141, 0.77045393, 0.28097726, 0.6324734 , 0.06162585],
       [0.02416492, 0.08694826, 0.21949649, 0.20122716, 0.88249181,
        0.50616996, 0.8993781 , 0.95710921, 0.63770942, 0.68241222],
       [0.90908665, 0.76966646, 0.59840982, 0.33413361, 0.13269855,
        0.97599439, 0.39864375, 0.79847966, 0.2953324 , 0.12213067],
       [0.20645804, 0.88750785, 0.15048484, 0.30047141, 0.43458025,
        0.35494665, 0.69618276, 0.84114557, 0.55308782, 0.84199618],
       [0.54028794, 0.00700666, 0.461035  , 0.48441452, 0.40104222,
        0.15401944, 0.77371657, 0.58172054, 0.47219237, 0.19823101],
       [0.22885836, 0.68100159, 0.3947311

In [153]:
y=rand(11)

In [154]:
y

array([0.58433318, 0.38765657, 0.30371859, 0.61082665, 0.9502889 ,
       0.48613431, 0.02475619, 0.68861335, 0.19321064, 0.43622772,
       0.9774209 ])

In [155]:
x.shape

(11, 10)

In [156]:
y=y.reshape(len(y),1)
y.shape

(11, 1)

In [157]:
w=np.array([[1,1,1,1,1,1,1,1,1,1]])
learning_rate=0.01
n=x.shape[0]

In [158]:
def gradient(x,y,w,n,learning_rate):
    dldw=0
    for xi, yi in zip(x,y):
        dldw+=(-2/n) * np.transpose(xi) * (yi-(xi*w))
    w=w- (learning_rate*dldw)
    return w

In [159]:
for epochs in range(300):
    w=gradient(x,y,w,n,learning_rate)
    loss=(1/n)*((y-(x*w))**2)
    print(loss)

[[1.56697953e-02 1.56236514e-02 1.56633957e-02 1.55591007e-02
  1.55831127e-02 1.55137593e-02 1.54993131e-02 1.54831852e-02
  1.55534252e-02 1.56690571e-02]
 [4.86679216e-03 3.93001271e-03 9.50671830e-04 2.77491838e-02
  9.26442251e-03 1.36501598e-03 5.01656539e-03 2.57543246e-02
  1.71122490e-04 9.19706106e-04]
 [1.66345313e-03 9.49625755e-04 2.25629090e-03 1.29870467e-02
  1.45210356e-04 3.16446644e-02 1.96237969e-02 5.05343791e-05
  9.74848206e-03 5.32945069e-03]
 [3.12896381e-02 2.49590358e-02 1.39308083e-02 1.52814219e-02
  6.63776461e-03 1.02060861e-03 7.43961993e-03 1.07225550e-02
  5.94955972e-05 4.61391596e-04]
 [1.57718207e-04 2.99389744e-03 1.12784659e-02 3.45869472e-02
  6.08009930e-02 4.89308223e-05 2.77752065e-02 2.16116176e-03
  3.90688477e-02 6.23589227e-02]
 [7.11599821e-03 1.45739347e-02 1.02471938e-02 3.15365287e-03
  2.48366674e-04 1.58637349e-03 3.93790735e-03 1.12966221e-02
  3.93909544e-04 1.14850388e-02]
 [2.41361248e-02 2.86655433e-05 1.72823714e-02 1.91283730e