Everything up to "Gradient Descent Vector Style" is copied from Nicholas Renotte


Source:https://www.youtube.com/watch?v=Souzjv6WfrY&t=816s

In [117]:
import numpy as np

In [118]:
x=np.random.randn(10,1)

In [119]:
print(x)

[[-0.25900344]
 [ 0.84519776]
 [ 0.99586785]
 [ 0.65810021]
 [-0.30027708]
 [ 0.78027012]
 [ 0.02491361]
 [ 0.11546709]
 [-1.26499148]
 [-0.30144655]]


In [120]:
y=2*x + np.random.rand()
##random calculation to represent y

In [121]:
y

array([[ 0.35669858],
       [ 2.56510099],
       [ 2.86644115],
       [ 2.19090588],
       [ 0.27415129],
       [ 2.4352457 ],
       [ 0.92453267],
       [ 1.10563963],
       [-1.6552775 ],
       [ 0.27181236]])

In [122]:
w=1.0
b=1.0
learning_rate=0.1

#  Gradient Descent (non-vector way)

In [123]:
def descent(x,y,w,b,learning_rate):
    dldw=0.0
    dldb=0.0
    N=x.shape[0]
    
    
    for xi, yi in zip(x,y):
        dldw +=-2*xi * (yi-(w*xi+b))
        dldb+= -2 * (yi-(w*xi+b))
        
    w=w-learning_rate*(1/N) * dldw
    b= b-learning_rate*(1/N) * dldb
    return w,b

In [124]:
for epoch in range(300):
    w, b= descent(x,y,w,b,learning_rate)
    yhat=w*x + b
    

#  Gradient Descent Vector Style

In [125]:
import numpy as np

In [126]:
x=np.array

In [127]:
from numpy.random import rand

In [128]:
x=rand(100)

In [129]:
intercept.shape

(1, 10)

In [130]:
x=x.reshape(10,10)
x

array([[0.90675408, 0.9472858 , 0.33092167, 0.99992436, 0.83866586,
        0.3481145 , 0.81588462, 0.48025523, 0.36399849, 0.02654899],
       [0.69092507, 0.20053681, 0.63805698, 0.99844724, 0.81617481,
        0.04685227, 0.80784702, 0.94169708, 0.81861978, 0.43534468],
       [0.98808771, 0.27429937, 0.96959785, 0.60206089, 0.30684697,
        0.61611191, 0.61967902, 0.84155718, 0.68968313, 0.0441687 ],
       [0.99213773, 0.69707292, 0.20178725, 0.90024685, 0.36849542,
        0.00226046, 0.5159953 , 0.76243413, 0.65144704, 0.68231698],
       [0.64164762, 0.5889684 , 0.01742635, 0.88051236, 0.19129602,
        0.69385414, 0.20406988, 0.15830464, 0.53732084, 0.44965629],
       [0.90121484, 0.01174339, 0.19613094, 0.75121609, 0.07184028,
        0.50823571, 0.38532708, 0.3236476 , 0.10259086, 0.45624054],
       [0.13075537, 0.38148818, 0.5611325 , 0.61292863, 0.15406999,
        0.62918745, 0.73377945, 0.88574846, 0.98331701, 0.50306578],
       [0.0519242 , 0.91563228, 0.2600486

In [131]:
intercept=np.array([[1,1,1,1,1,1,1,1,1,1]])

In [132]:
intercept.shape

(1, 10)

In [133]:
x=np.concatenate((intercept,x))

In [134]:
x

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.90675408, 0.9472858 , 0.33092167, 0.99992436, 0.83866586,
        0.3481145 , 0.81588462, 0.48025523, 0.36399849, 0.02654899],
       [0.69092507, 0.20053681, 0.63805698, 0.99844724, 0.81617481,
        0.04685227, 0.80784702, 0.94169708, 0.81861978, 0.43534468],
       [0.98808771, 0.27429937, 0.96959785, 0.60206089, 0.30684697,
        0.61611191, 0.61967902, 0.84155718, 0.68968313, 0.0441687 ],
       [0.99213773, 0.69707292, 0.20178725, 0.90024685, 0.36849542,
        0.00226046, 0.5159953 , 0.76243413, 0.65144704, 0.68231698],
       [0.64164762, 0.5889684 , 0.01742635, 0.88051236, 0.19129602,
        0.69385414, 0.20406988, 0.15830464, 0.53732084, 0.44965629],
       [0.90121484, 0.01174339, 0.19613094, 0.75121609, 0.07184028,
        0.50823571, 0.38532708, 0.3236476 , 0.10259086, 0.45624054],
       [0.13075537, 0.38148818, 0.5611325

In [135]:
y=rand(11)

In [136]:
y

array([0.73580913, 0.83691345, 0.82569445, 0.57141814, 0.24212134,
       0.88503823, 0.15768784, 0.9419712 , 0.53347848, 0.69668617,
       0.90166005])

In [137]:
x.shape

(11, 10)

In [138]:
y=y.reshape(len(y),1)
y.shape

(11, 1)

In [139]:
w=np.array([[1,1,1,1,1,1,1,1,1,1]])
learning_rate=0.01
n=x.shape[0]

In [140]:
def gradient(x,y,w,n,learning_rate):
    dldw=0
    for xi, yi in zip(x,y):
        dldw+=(-2/n) * np.transpose(xi) * (yi-(xi*w))
    w=w- (learning_rate*dldw)
    return w

In [141]:
for epochs in range(300):
    w=gradient(x,y,w,n,learning_rate)
    print(w)
    loss=(1/n)*((y-(x*w))**2)
    print(loss)

[[0.99725805 0.99958968 1.00003864 0.99701885 0.99999353 1.00025129
  0.99976136 0.99851738 0.99991498 1.000525  ]]
[[6.21413950e-03 6.32547050e-03 6.34702114e-03 6.20277415e-03
  6.34485404e-03 6.35724111e-03 6.33370710e-03 6.27414741e-03
  6.34108171e-03 6.37040795e-03]
 [4.12419054e-04 1.09967326e-03 2.32740670e-02 2.32814513e-03
  2.77451449e-07 2.17126278e-02 4.09489120e-05 1.16103184e-02
  2.03343481e-02 5.96970872e-02]
 [1.69791016e-03 3.55386330e-02 3.19987002e-03 2.62036176e-03
  8.24764392e-06 5.51433456e-02 2.95863069e-05 1.19405797e-03
  4.64005788e-06 1.38358697e-02]
 [1.55784645e-02 8.03149662e-03 1.44160835e-02 7.56547134e-05
  6.36354149e-03 1.82854194e-04 2.10441877e-04 6.57295853e-03
  1.27024921e-03 2.52697751e-02]
 [5.07683009e-02 1.87927971e-02 1.47837258e-04 3.90548980e-02
  1.45180061e-03 5.23026977e-03 6.81268321e-03 2.45045782e-02
  1.52274724e-02 1.76443365e-02]
 [5.46350123e-03 7.98186413e-03 6.84317462e-02 4.64855746e-06
  4.37527254e-02 3.31679266e-03 4.216

[[0.78240051 0.96089381 1.00386277 0.78745403 0.99936501 1.02625706
  0.97797681 0.87008007 0.99238353 1.06317759]]
[[1.97341467e-04 4.60573756e-03 6.53206821e-03 2.42472291e-04
  6.31469976e-03 7.66909058e-03 5.33138008e-03 1.63897136e-03
  5.98458380e-03 9.74273662e-03]
 [1.47711293e-03 4.88812699e-04 2.31577927e-02 2.22920877e-04
  1.35279498e-07 2.09156606e-02 1.38252942e-04 1.59641247e-02
  2.05707679e-02 5.94522647e-02]
 [7.39001621e-03 3.64262577e-02 3.11717905e-03 1.41576405e-04
  9.15995607e-06 5.49709442e-02 1.15465851e-04 3.65713002e-06
  1.61042928e-05 1.19688216e-02]
 [3.69705775e-03 8.61535464e-03 1.46857943e-02 8.61067415e-04
  6.37282227e-03 3.36844137e-04 1.08918089e-04 2.35072021e-03
  1.16106550e-03 2.50052014e-02]
 [2.59356754e-02 1.66291095e-02 1.42233540e-04 1.98077391e-02
  1.44648391e-03 5.22770642e-03 6.26468654e-03 1.61325277e-02
  1.48645663e-02 2.12346891e-02]
 [1.33362557e-02 9.25692517e-03 6.84212342e-02 3.33994482e-03
  4.37678925e-02 2.71973387e-03 4.271