Everything up to "Gradient Descent Vector Style" is copied from Nicholas Renotte


Source:https://www.youtube.com/watch?v=Souzjv6WfrY&t=816s

In [44]:
import numpy as np

In [45]:
x=np.random.randn(10,1)

In [46]:
print(x)

[[-0.42122173]
 [-0.90439002]
 [-1.03146167]
 [ 1.44434819]
 [-0.76087887]
 [-0.09741724]
 [-1.15225687]
 [-2.50161404]
 [ 0.46179376]
 [-1.21070976]]


In [47]:
y=2*x + np.random.rand()
##random calculation to represent y

In [48]:
y

array([[-0.48175929],
       [-1.44809587],
       [-1.70223917],
       [ 3.24938054],
       [-1.16107356],
       [ 0.16584968],
       [-1.94382957],
       [-4.6425439 ],
       [ 1.28427169],
       [-2.06073536]])

In [49]:
w=1.0
b=1.0
learning_rate=0.1

#  Gradient Descent (non-vector way)

In [50]:
def descent(x,y,w,b,learning_rate):
    dldw=0.0
    dldb=0.0
    N=x.shape[0]
    
    
    for xi, yi in zip(x,y):
        dldw +=-2*xi * (yi-(w*xi+b))
        dldb+= -2 * (yi-(w*xi+b))
        
    w=w-learning_rate*(1/N) * dldw
    b= b-learning_rate*(1/N) * dldb
    return w,b

In [54]:
for epoch in range(300):
    w, b= descent(x,y,w,b,learning_rate)
    yhat=w*x + b
    print(w,b)
    

[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36068417]
[2.] [0.36

#  Gradient Descent Vector Style

In [83]:
import numpy as np

In [84]:
x=np.array

In [85]:
from numpy.random import rand

In [86]:
x=rand(100)

In [87]:
intercept.shape

(1, 10)

In [88]:
x=x.reshape(10,10)
x

array([[0.05942849, 0.29748183, 0.02290055, 0.77699713, 0.61328885,
        0.31204154, 0.70712576, 0.24866214, 0.32601754, 0.16528382],
       [0.53204297, 0.68041885, 0.3946442 , 0.37591032, 0.37642652,
        0.61206207, 0.29481596, 0.83626429, 0.05675318, 0.19494116],
       [0.37894744, 0.82269303, 0.74127023, 0.90805445, 0.80762192,
        0.26803105, 0.2544114 , 0.88825557, 0.90499655, 0.37003192],
       [0.88823985, 0.26797897, 0.45847465, 0.11807325, 0.7369848 ,
        0.99369944, 0.25715352, 0.34641118, 0.87468456, 0.19417142],
       [0.03799547, 0.95556814, 0.51264994, 0.2882956 , 0.15673332,
        0.58501298, 0.18731617, 0.660286  , 0.95887959, 0.13172783],
       [0.35820787, 0.2327696 , 0.72223117, 0.43615171, 0.35946916,
        0.60094138, 0.61587644, 0.83928195, 0.34146985, 0.44572563],
       [0.19209419, 0.15509455, 0.75746525, 0.43264377, 0.563898  ,
        0.92070574, 0.00157624, 0.9651152 , 0.76516997, 0.88938995],
       [0.52567088, 0.75728933, 0.0700460

In [89]:
intercept=np.array([[1,1,1,1,1,1,1,1,1,1]])

In [90]:
intercept.shape

(1, 10)

In [91]:
x=np.concatenate((intercept,x))

In [92]:
x

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.05942849, 0.29748183, 0.02290055, 0.77699713, 0.61328885,
        0.31204154, 0.70712576, 0.24866214, 0.32601754, 0.16528382],
       [0.53204297, 0.68041885, 0.3946442 , 0.37591032, 0.37642652,
        0.61206207, 0.29481596, 0.83626429, 0.05675318, 0.19494116],
       [0.37894744, 0.82269303, 0.74127023, 0.90805445, 0.80762192,
        0.26803105, 0.2544114 , 0.88825557, 0.90499655, 0.37003192],
       [0.88823985, 0.26797897, 0.45847465, 0.11807325, 0.7369848 ,
        0.99369944, 0.25715352, 0.34641118, 0.87468456, 0.19417142],
       [0.03799547, 0.95556814, 0.51264994, 0.2882956 , 0.15673332,
        0.58501298, 0.18731617, 0.660286  , 0.95887959, 0.13172783],
       [0.35820787, 0.2327696 , 0.72223117, 0.43615171, 0.35946916,
        0.60094138, 0.61587644, 0.83928195, 0.34146985, 0.44572563],
       [0.19209419, 0.15509455, 0.7574652

In [93]:
y=rand(11)

In [94]:
y

array([0.02644751, 0.84850788, 0.27253332, 0.03993781, 0.05412808,
       0.27139901, 0.36667123, 0.7357269 , 0.62939489, 0.43210484,
       0.0730191 ])

In [95]:
x.shape

(11, 10)

In [96]:
y=y.reshape(len(y),1)
y.shape

(11, 1)

In [97]:
w=np.array([[1,1,1,1,1,1,1,1,1,1]])
learning_rate=0.01
n=x.shape[0]

In [98]:
def gradient(x,y,w,n,learning_rate):
    dldw=0
    for xi, yi in zip(x,y):
        dldw+=(-2/n) * np.transpose(xi) * (yi-(xi*w))
    w=w- (learning_rate*dldw)
    return w

In [99]:
for epochs in range(500):
    w=gradient(x,y,w,n,learning_rate)
    print(w)
    loss=(1/n)*((y-(x*w))**2)
    print(loss)

[[0.99532373 0.99412457 0.9957919  0.99615629 0.99518329 0.99513908
  0.99573212 0.99400142 0.99479829 0.99632129]]
[[8.53382838e-02 8.51271719e-02 8.54207766e-02 8.54850105e-02
  8.53135460e-02 8.53057602e-02 8.54102402e-02 8.51055065e-02
  8.52457479e-02 8.55141045e-02]
 [5.66440854e-02 2.77780871e-02 6.19805997e-02 5.04531650e-04
  5.15694631e-03 2.63114426e-02 1.89557954e-03 3.28733288e-02
  2.49791964e-02 4.25114841e-02]
 [6.00546752e-03 1.48295763e-02 1.31893150e-03 9.44559536e-04
  9.47303605e-04 1.02971188e-02 4.01841247e-05 2.83783617e-02
  4.24441423e-03 5.57485877e-04]
 [1.03390165e-02 5.50147220e-02 4.43183195e-02 6.79617014e-02
  5.30346651e-02 4.67580619e-03 4.13948657e-03 6.46028445e-02
  6.72912923e-02 9.82411865e-03]
 [6.26209529e-02 4.09647890e-03 1.47217862e-02 3.66468109e-04
  4.19507119e-02 7.94309878e-02 3.70680850e-03 7.65627417e-03
  6.05333466e-02 1.76477997e-03]
 [4.96001679e-03 4.18578698e-02 5.19688837e-03 2.26614445e-05
  1.21108377e-03 8.77983287e-03 6.550

  3.32247196e-04 1.20646802e-02]]
[[0.40393742 0.38363268 0.44005331 0.52123801 0.45276773 0.44935931
  0.51365264 0.4439953  0.40456234 0.53041026]]
[[1.29544207e-02 1.15982952e-02 1.55517959e-02 2.22561485e-02
  1.65226300e-02 1.62594896e-02 2.15789854e-02 1.58496502e-02
  1.29973476e-02 2.30889503e-02]
 [6.18003957e-02 4.90290945e-02 6.39059602e-02 1.78817140e-02
  2.96224940e-02 4.56066784e-02 2.14097475e-02 4.95269202e-02
  4.66849864e-02 5.26251784e-02]
 [3.01837161e-04 1.20277590e-05 8.88640498e-04 5.33338963e-04
  9.47665005e-04 5.69305399e-07 1.33320798e-03 8.86758763e-04
  5.66243096e-03 2.60058977e-03]
 [1.16355736e-03 6.90874783e-03 7.44955799e-03 1.70739651e-02
  9.64529976e-03 5.89178581e-04 7.48543669e-04 1.14209261e-02
  9.67270283e-03 2.22175977e-03]
 [8.43826385e-03 2.15408199e-04 1.98120006e-03 4.99998206e-06
  7.10462880e-03 1.39979788e-02 5.52516777e-04 9.03225027e-04
  8.16744371e-03 2.17048821e-04]
 [5.96020229e-03 8.23707896e-04 1.90742065e-04 1.33382587e-03
  3

  0.48150249 0.42469964 0.36469143 0.48807286]]
[[9.54055681e-03 9.61920378e-03 1.16139665e-02 1.87652965e-02
  1.38596929e-02 1.36242961e-02 1.88250028e-02 1.44186140e-02
  1.04008134e-02 1.93725423e-02]
 [6.22782628e-02 5.03043342e-02 6.41022331e-02 2.05064398e-02
  3.19492284e-02 4.70560163e-02 2.34626789e-02 5.01729208e-02
  4.83939801e-02 5.35976514e-02]
 [6.74001938e-04 1.00245491e-04 1.33187361e-03 7.66163646e-04
  1.21483882e-03 3.42148598e-05 1.55007244e-03 6.20668829e-04
  5.76557540e-03 2.86058554e-03]
 [7.83669355e-04 5.65599448e-03 5.43974824e-03 1.43018910e-02
  8.00622680e-03 4.57150090e-04 6.19679099e-04 1.03430905e-02
  7.65108051e-03 1.79877885e-03]
 [6.00970836e-03 1.46395765e-04 1.35017278e-03 6.33220611e-07
  5.82471287e-03 1.15759290e-02 4.41542920e-04 7.86147974e-04
  6.37743787e-03 1.50159016e-04]
 [6.05527669e-03 3.80632619e-04 5.06005977e-04 1.60306904e-03
  3.85992301e-03 7.88595682e-05 2.98504950e-03 7.40331924e-06
  5.57298997e-04 3.89936271e-03]
 [5.286871